name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install depot_tools
        run: |
          mkdir depot
          cd depot
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=$PATH:$(pwd)

      - name: Get Chromium
        run: |
          cd ..
          mkdir chro
          cd chro
          git clone --depth 100 -b 49.0.2623.112 https://chromium.googlesource.com/chromium/src.git src
          gclient config --unmanaged https://chromium.googlesource.com/chromium/src.git
          gclient sync

